spring:
  application:
    name: teamHealthTrack
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://teamhealthtrack-prod-v2.czokgsgw4vpm.us-east-1.rds.amazonaws.com:5432/team_health_track
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    username: ${username}
    password: ${password}
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    table: migrations

server:
  port: ${SERVER_PORT:8080}

app:
  name: SandBox task API
  api:
    title: Spring Boot APIs
    version: 1.0.0
    description: Spring Boot APIs description
    base-package: org.health.track
    contact-name: Norayr Gharibyan
    contact-email: norayrgh@gmail.com
    swagger:
      enable: false
