spring:
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  application:
    name: teamHealthTrack
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${JDBC_URL:localhost}:${JDBC_PORT:5432}/${DATABASE_NAME:teamHealthTrack}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    username: ${SPRING_DATASOURCE_USERNAME:sandbox}
    password: ${SPRING_DATASOURCE_PASSWORD:sandbox}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    table: migrations

server:
  port: ${SERVER_PORT:8080}

app:
  name: SandBox task API
  api:
    title: Spring Boot APIs
    version: 1.0.0
    description: Spring Boot APIs description
    base-package: org.health.track
    contact-name: Norayr Gharibyan
    contact-email: norayrgh@gmail.com
    swagger:
      enable: true